# Generated by Django 5.1.3 on 2024-11-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='ranks',
            field=models.CharField(default='0.0', max_length=5),
        ),
    ]
